services:
  accountservice:
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    container_name: account-service-backend
    environment:   
      - ASPNETCORE_URLS=http://+:80
      - JwtSettings__Authority=http://keycloak:8888/realms/account_service
      - JwtSettings__Audience=account
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AccountServiceDbContext=Host=db;Port=5432;Database=accountService;Username=postgres;Password=123
    ports:
      - "80:80"
    depends_on:
      - keycloak
      - db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8888:8888"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8888
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_URL: http://keycloak:8888
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_ADMIN_URL: http://localhost:8888
    volumes:
      - ./account_service-realm.json:/opt/keycloak/data/import/account_service-realm.json
  
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: accountService
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      
volumes:
  keycloak-data:
    
networks:
  app-network:
    driver: bridge