version: '3.4'

services:
  accountservice:
    image: ${DOCKER_REGISTRY-}accountservice
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__Authority=http://keycloak:9999/realms/account_service
      - JwtSettings__Audience=account
    ports:
      - "46320:80"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-debug
    command: start-dev --import-realm
    ports:
      - "9999:9999"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9999
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_URL: http://keycloak:9999
      KC_HOSTNAME_ADMIN_URL: http://localhost:9999
      KC_HOSTNAME_STRICT: false
    volumes:
      - ./account_service-realm.json:/opt/keycloak/data/import/account_service-realm.json
